---

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-cache madison lxd
  - sudo apt-get install -y lxd=2.10.1-0ubuntu1~ubuntu14.04.1~ppa1
  - sudo lxd init --auto --storage-backend=dir || true
  - sudo lxc network create testbr0
  - sudo lxc network attach-profile testbr0 default eth0

  - sudo apt-get install snapd
  - sudo snap install --classic snapcraft

script:
  - snapcraft cleanbuild
