---

sudo: required
dist: trusty

before_install:
  - sudo apt update
  - sudo apt-cache madison lxd
  - sudo apt-get install -t trusty-backports -y lxd
  - sudo lxd init --auto
  - sudo dpkg-reconfigure -p medium lxd
  - sudo apt install -y snapd

script:
  - sudo lxc launch ubuntu:16.04 u1
  - sudo snap list
  - snap list
