---

sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-get install -y lxd
  - sudo lxd init --auto --storage-backend=dir || true
  - sudo lxc network create testbr0
  - sudo lxc network attach-profile testbr0 default eth0

  - sudo apt-get install snapcraft

script:
  - snapcraft cleanbuild
