---

name: springlobby-nsg
adopt-info: springlobby
summary: SpringLobby is a free cross-platform lobby client for the Spring RTS project.
description: |
  SpringLobby is the most easiest and most popular to way to launch the Spring RTS game
  engine. This snap is based on the upstream lobby but a few teaks has been added for
  a better snappy experience. For more info see https://github.com/nsg/snap-springlobby

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  springlobby-nsg:
    command: bin/launch
    plugs:
      - x11
      - network
      - opengl
      - unity7
      - desktop
      - wayland
      - pulseaudio
  pr-downloader:
    command: pr-downloader
    plugs:
      - network

parts:
  desktop-gtk2:
    stage:
      - -usr/share/doc/libavahi-common-data/changelog.Debian.gz
      - -usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
      - -usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
  springlobby:
    plugin: cmake
    source: https://github.com/springlobby/springlobby.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    configflags:
      - -DSPRINGLOBBY_REV=$SNAPCRAFT_PROJECT_VERSION
    override-pull: |
        snapcraftctl pull
        git checkout "$(git describe --tags --abbrev=0)"
        snapcraftctl set-version "$(git describe --tags --abbrev=0)"
    override-build: |
        set -ex
        cat > ../src/cmake/config.h <<EOF
        /* generated by snapcraft */
        #ifndef SPRINGLOBBY_HEADERGUARD_CONFIG_H
        #define SPRINGLOBBY_HEADERGUARD_CONFIG_H
        #undef VERSION
        #define VERSION "$(git describe --tags --abbrev=0)"
        #endif
        EOF
        snapcraftctl build
    after:
      - desktop-gtk2
    build-packages:
      - build-essential
      - libwxgtk3.0-dev
      - libcurl4-openssl-dev
      - libalure-dev
      - libboost-thread-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libpng12-dev
      - libssl-dev

    stage-packages:
      - libwxgtk3.0-0v5
      - libalure1
      - libboost-thread1.58.0
      - libboost-filesystem1.58.0
      - libboost-system1.58.0
      - libpng12-0
      - libssl1.0.0
      - libsdl2-2.0-0
      - libglu1-mesa
      - libpulse0
      - libvorbisfile3
      - libmpg123-0
      - libdumb1
      - libmodplug1
      - libfluidsynth1

  pr-downloader:
    plugin: cmake
    source: https://github.com/spring/pr-downloader.git
    build-packages:
      - libcurl4-openssl-dev
      - libjsoncpp-dev
      - libboost-thread1.58-dev
      - libboost-system1.58-dev
      - libboost-filesystem1.58-dev
      - liblua5.1-0-dev
      - libzip-dev
      - zlib1g-dev

  launch:
    plugin: dump
    source: bin
    organize:
      launch: bin/launch
